/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Offer {
  'id' : OfferId,
  'fare' : bigint,
  'rideId' : RideId,
  'accepted' : boolean,
  'driver' : Principal,
}
export type OfferId = bigint;
export type RideId = bigint;
export interface RideRequest {
  'id' : RideId,
  'status' : RideStatus,
  'passenger' : Principal,
  'destination' : string,
  'proposedFare' : bigint,
  'acceptedOffer' : [] | [OfferId],
  'pickupLocation' : string,
}
export type RideStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null } |
  { 'searching' : null };
export interface UserProfile {
  'name' : string,
  'carInfo' : [] | [string],
  'rating' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOffer' : ActorMethod<[RideId, bigint], OfferId>,
  'createRideRequest' : ActorMethod<[string, string, bigint], RideId>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'getAllRideRequests' : ActorMethod<[], Array<RideRequest>>,
  'getAllRideRequestsByProposedFare' : ActorMethod<[], Array<RideRequest>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOffersForRide' : ActorMethod<[bigint], Array<Offer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];