/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RideId = IDL.Nat;
export const OfferId = IDL.Nat;
export const Offer = IDL.Record({
  'id' : OfferId,
  'fare' : IDL.Nat,
  'rideId' : RideId,
  'accepted' : IDL.Bool,
  'driver' : IDL.Principal,
});
export const RideStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
  'searching' : IDL.Null,
});
export const RideRequest = IDL.Record({
  'id' : RideId,
  'status' : RideStatus,
  'passenger' : IDL.Principal,
  'destination' : IDL.Text,
  'proposedFare' : IDL.Nat,
  'acceptedOffer' : IDL.Opt(OfferId),
  'pickupLocation' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'carInfo' : IDL.Opt(IDL.Text),
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOffer' : IDL.Func([RideId, IDL.Nat], [OfferId], []),
  'createRideRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [RideId], []),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAllRideRequests' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
  'getAllRideRequestsByProposedFare' : IDL.Func(
      [],
      [IDL.Vec(RideRequest)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOffersForRide' : IDL.Func([IDL.Nat], [IDL.Vec(Offer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RideId = IDL.Nat;
  const OfferId = IDL.Nat;
  const Offer = IDL.Record({
    'id' : OfferId,
    'fare' : IDL.Nat,
    'rideId' : RideId,
    'accepted' : IDL.Bool,
    'driver' : IDL.Principal,
  });
  const RideStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
    'searching' : IDL.Null,
  });
  const RideRequest = IDL.Record({
    'id' : RideId,
    'status' : RideStatus,
    'passenger' : IDL.Principal,
    'destination' : IDL.Text,
    'proposedFare' : IDL.Nat,
    'acceptedOffer' : IDL.Opt(OfferId),
    'pickupLocation' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'carInfo' : IDL.Opt(IDL.Text),
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOffer' : IDL.Func([RideId, IDL.Nat], [OfferId], []),
    'createRideRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [RideId], []),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAllRideRequests' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
    'getAllRideRequestsByProposedFare' : IDL.Func(
        [],
        [IDL.Vec(RideRequest)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOffersForRide' : IDL.Func([IDL.Nat], [IDL.Vec(Offer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };